
CREATE TABLE IF NOT EXISTS USERS (
    USER_ID INTEGER PRIMARY KEY AUTOINCREMENT,
    FULL_NAME VARCHAR(255) NOT NULL,
    EMAIL VARCHAR(255) UNIQUE NOT NULL,
    PASSWORD_HASH VARCHAR(255) NOT NULL,
    ROLE VARCHAR(50) DEFAULT 'USER',
    PHONE VARCHAR(20),
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS VENDORS (
    VENDOR_ID INTEGER PRIMARY KEY AUTOINCREMENT,
    USER_ID INT NOT NULL,
    SHOP_NAME VARCHAR(255) NOT NULL,
    IS_VERIFIED BOOLEAN DEFAULT FALSE,
    FOREIGN KEY (USER_ID) REFERENCES USERS(USER_ID) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS CATEGORIES (
    CAT_ID INTEGER PRIMARY KEY AUTOINCREMENT,
    CAT_NAME VARCHAR(255) NOT NULL,
    CAT_SLUG VARCHAR(255) UNIQUE NOT NULL
);

CREATE TABLE IF NOT EXISTS PRODUCTS (
    PROD_ID INTEGER PRIMARY KEY AUTOINCREMENT,
    VENDOR_ID INT NOT NULL,
    CAT_ID INT NOT NULL,
    PROD_NAME VARCHAR(255) NOT NULL,
    DESCRIPTION TEXT,
    PRICE DECIMAL(10, 2) NOT NULL,
    STOCK_QTY INT DEFAULT 0,
    RATING DECIMAL(3, 2),
    REVIEW_COUNT INT DEFAULT 0,
    IMAGE_URL VARCHAR(500),
    DISCOUNT_PCT DECIMAL(5, 2) DEFAULT 0,
    IS_ACTIVE BOOLEAN DEFAULT TRUE,
    IS_FEATURED BOOLEAN DEFAULT FALSE,
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (VENDOR_ID) REFERENCES VENDORS(VENDOR_ID) ON DELETE CASCADE,
    FOREIGN KEY (CAT_ID) REFERENCES CATEGORIES(CAT_ID) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS ORDERS (
    ORDER_ID INTEGER PRIMARY KEY AUTOINCREMENT,
    CUSTOMER_ID INT NOT NULL,
    TOTAL_AMOUNT DECIMAL(10, 2) NOT NULL,
    DISCOUNT_AMOUNT DECIMAL(10, 2) DEFAULT 0,
    DELIVERY_CHARGE DECIMAL(10, 2) DEFAULT 0,
    FINAL_AMOUNT DECIMAL(10, 2) NOT NULL,
    PAYMENT_STATUS VARCHAR(50) DEFAULT 'PENDING',
    ORDER_STATUS VARCHAR(50) DEFAULT 'PENDING',
    ADDRESS_LINE1 VARCHAR(255),
    CITY VARCHAR(100),
    STATE VARCHAR(100),
    POSTAL_CODE VARCHAR(20),
    CONTACT_PHONE VARCHAR(20),
    ORDERED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (CUSTOMER_ID) REFERENCES USERS(USER_ID) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS ORDER_ITEMS (
    ITEM_ID INTEGER PRIMARY KEY AUTOINCREMENT,
    ORDER_ID INT NOT NULL,
    PROD_ID INT NOT NULL,
    QUANTITY INT NOT NULL,
    UNIT_PRICE DECIMAL(10, 2) NOT NULL,
    FOREIGN KEY (ORDER_ID) REFERENCES ORDERS(ORDER_ID) ON DELETE CASCADE,
    FOREIGN KEY (PROD_ID) REFERENCES PRODUCTS(PROD_ID) ON DELETE CASCADE
);
